server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1